# _config.yml

# Site Ayarları
title: FTR Değerlendirme Araçları ve Bilgi Portalı
email: iletisim@ornek.com # KENDİ E-POSTANIZI GİRİN VEYA YORUM SATIRI YAPIN
repository: fr3sby2/ftr-web-olcekler
description: >-
  Fizik Tedavi ve Rehabilitasyon (FTR) öğrencileri ve profesyonelleri için
  kapsamlı bir Türkçe kaynak. Güncel değerlendirme ölçekleri,
  sık karşılaşılan hastalıklar hakkında bilgiler ve klinik pratik araçları.
baseurl: "/ftr-web-olcekler" # Repository adıyla eşleşiyor, doğru.
url: "https://fr3sby2.github.io" # Kullanıcı adıyla güncellendi, doğru.
github_username: fr3sby2

# Build Ayarları
markdown: kramdown
highlighter: rouge
permalink: pretty

# Koleksiyonlar
collections:
  assessments:
    output: true
    permalink: /degerlendirme-araclari/:basename/
  diseases:
    output: true
    permalink: /hastaliklar/:basename/

# Varsayılanlar
defaults:
  - scope:
      path: ""
      type: "assessments"
    values:
      layout: "assessment"
      # sidebar_nav: /assessments/ # Bu aktif değilse kaldırılabilir
  - scope:
      path: ""
      type: "diseases"
    values:
      layout: "disease"
  - scope:
      path: "pages"
      type: pages
    values:
      layout: "page"

# Eklentiler (Plugins)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
#  - github-metadata # YEREL HATAYI ÖNLEMEK İÇİN BU SATIRI YORUMA ALIN VEYA SİLİN (veya aşağıdaki 'exclude' yöntemini kullanın)

# Sass/SCSS Ayarları
sass:
  sass_dir: _sass # assets/css/main.scss kullanıyorsanız bu satıra gerek yok veya assets/scss yapın
  style: compressed

# Hariç Tutulacak Dosyalar ve Eklentiler (Yerel için)
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - create_*.py # Python betiklerini dışarıda bırak
  - kaynak_metin.txt # Kaynak metni dışarıda bırak
  - "*.env" # .env dosyasını dışarıda bırak
#  - vendor/ # Eğer bundle install --path vendor/bundle kullanıyorsanız

# --- YEREL HATAYI ÖNLEMEK İÇİN EKSTRA AYAR ---
# Eğer yukarıda plugins altından github-metadata'yı silmediyseniz,
# bu ayar yerelde çalıştırırken hata vermesini engelleyebilir.
# GitHub Pages'de yayınlarken bu ayar genellikle göz ardı edilir.
# _config.yml dosyasının sonuna ekleyin

# GitHub Metadata eklentisini yerel derlemede tamamen devre dışı bırak
github: false